# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: batches.infinispan.org
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
        - "v1"
      # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
      # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
      caBundle: Cg==
      clientConfig:
        service:
          namespace: system
          name: webhook-service
          path: /convert
          port: 443